# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16MXkPNXse3VGY-QLzgk1-HQzkhfRERUc
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

df = pd.read_csv('car_data.csv')

#Part 1
x = df[['Mileage']]
y = df[['Price']]

model=linear_model.LinearRegression()
model.fit(x,y)

print('intercept:', model.intercept_)
print('coefficients:', model.coef_)
print('r-squared:', model.score(x, y))

plt.scatter(x, y, color='r')
plt.plot(x, model.predict(x))
plt.xlabel('Mileage')
plt.ylabel('Price')
plt.title('Mileage vs Price')

# Part 2

feature = ['Mileage', 'Cylinder', 'Liter', 'Doors', 'Cruise', 'Sound', 'Leather']
x = df[feature]
y = df[['Price']]

model=linear_model.LinearRegression()

model.fit(x,y)
print('intercept:', model.intercept_)
print('coefficients:', model.coef_)

print('r-squared: ', model.score(x, y))