# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16MXkPNXse3VGY-QLzgk1-HQzkhfRERUc
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

df = pd.read_csv('train.csv')

x = df[['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT']]
y = df[['MEDV']]

model=linear_model.LinearRegression()
model.fit(x,y)
r_sqaure = model.score(x, y)
print("R-Square Score: ", all_five)
print("Intercept: ", model.intercept_)
print("Coefficient: ", model.coef_)

df_test = pd.read_csv('test.csv')
x = df_test[['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT']]
df_test['MEDV']=model.predict(x)